**Practical 9**
Aim: Use K-Means Clustering algorithm for dividing students based on some parameter.

In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
dataset = pd.read_csv('../input/fashion-mnist_train.csv')
labels = dataset['label'].values
features = dataset.drop(['label'],axis=1).values
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60000 entries, 0 to 59999
Columns: 785 entries, label to pixel784
dtypes: int64(785)
memory usage: 359.3 MB


In [3]:
dataset.head()

label  pixel1  pixel2    ...     pixel782  pixel783  pixel784
0      2       0       0    ...            0         0         0
1      9       0       0    ...            0         0         0
2      6       0       0    ...            0         0         0
3      0       0       0    ...            0         0         0
4      3       0       0    ...            0         0         0

[5 rows x 785 columns]

In [5]:
from sklearn.cluster import KMeans

In [6]:
kmeans = KMeans(n_clusters=2, random_state=0).fit(features)

In [7]:
kmeans.labels_

array([0, 1, 0, ..., 0, 0, 1], dtype=int32)

In [8]:
kmeans.cluster_centers_

array([[1.26903553e-03, 7.86802030e-03, 5.08248731e-02, ...,
        3.48832487e+00, 8.90958122e-01, 7.89974619e-02],
       [4.91573034e-04, 4.24859551e-03, 1.81882022e-02, ...,
        1.93981742e+00, 8.16292135e-01, 6.05688202e-02]])

In [20]:
y_pred = KMeans(n_clusters=2, random_state=0).fit_predict(features)

In [24]:
print(labels)

[[2]
 [9]
 [6]
 ...
 [8]
 [8]
 [7]]
